interface WidgetColorTemplateInterface {
  id: string;
  name: string;
  backgroundColor: string;
  textColor: string;
  thumbnailColor: string;
  buttonColor: string;
  buttonTextColor: string;
  thumbnailHeadingColor?: string;
  leafColor?: string;
  thumbnailTextColor?: string;
  hyperTextColor?: string;
  hyperTitleColor?: string;
  shareColor: string;
  titleColor: string;
  tryNowButtonTextColor: string;
  tryNowButtonColor: string;
  thumbnailTitleColor?: string;
}
export const palettes: WidgetColorTemplateInterface[] = [
  {
    id: "",
    name: "Custom Color Palette",
    backgroundColor: "",
    textColor: "",
    thumbnailColor: "",
    buttonColor: "",
    buttonTextColor: "",
    tryNowButtonColor: "",
    tryNowButtonTextColor: "",
    shareColor: "",
    titleColor: "", // Added titleColor property
  },
  {
    id: "1",
    name: "Orange Sunset palette",
    backgroundColor: "#E57402",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFFFFF",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#E57402",
    hyperTitleColor: "#000000",
    hyperTextColor: "#F5F5F5",
    shareColor: "#E57402",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonColor: "#E57402",
    tryNowButtonTextColor: "#FFFFFF",
    thumbnailTitleColor: "#000",
  },
  {
    id: "2",
    name: "Blackish Radiance Palette",
    backgroundColor: "#191717",
    textColor: "#F5F5F5",
    thumbnailColor: "#FFA500",
    buttonColor: "#FFA500",
    buttonTextColor: "#191717",
    hyperTextColor: "#FFA500",
    hyperTitleColor: "#F5F5F5",
    shareColor: "#FFA500",
    titleColor: "#F5F5F5", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#FFA500",
    thumbnailTitleColor: "#000",
  },
  {
    id: "3",
    name: "Beige Orchid Palette",
    thumbnailTitleColor: "#F5F5DC",
    backgroundColor: "#F5F5DC",
    textColor: "#333333",
    thumbnailColor: "#9932CC",
    buttonColor: "#9932CC",
    shareColor: "#9932CC",
    buttonTextColor: "#F5F5DC",
    hyperTextColor: "#9932CC",
    hyperTitleColor: "#333333",
    titleColor: "#333333", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#9932CC",
  },
  {
    id: "4",
    thumbnailTitleColor: "#BB2528",
    name: "Deep Red palette",
    backgroundColor: "#BB2528",
    shareColor: "#BB2528",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFFFFF",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#BB2528",
    hyperTextColor: "#FFFFFF",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#BB2528",
  },
  {
    id: "5",
    name: "Sunlit Blue Palette",
    backgroundColor: "#5A8DC3",
    shareColor: "#5A8DC3",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFD700",
    buttonColor: "#FFD700",
    buttonTextColor: "#000000",
    hyperTextColor: "#FFD700",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#5A8DC3",
    thumbnailTitleColor: "#000",
  },
  {
    id: "6",
    name: "Pure Aqua Palette",
    backgroundColor: "#FFF",
    textColor: "#333333",
    thumbnailColor: "#69C9D0",
    buttonColor: "#69C9D0",
    shareColor: "#69C9D0",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#69C9D0",
    hyperTitleColor: "#333333",
    titleColor: "#333333", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#69C9D0",
    thumbnailTitleColor: "#FFF",
  },
  {
    id: "7",
    name: "Bronze Peach Palette",
    backgroundColor: "#562C2C",
    shareColor: "#562C2C",
    textColor: "#FFFFFF",
    thumbnailColor: "#F5DFBB",
    buttonColor: "#F5DFBB",
    buttonTextColor: "#562C2C",
    hyperTextColor: "#F5DFBB",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#562C2C",
    thumbnailTitleColor: "#562C2C",
  },
  {
    id: "8",
    name: "Gray Blossom Palette",
    backgroundColor: "#333333",
    shareColor: "#333333",
    textColor: "#FFFFFF",
    thumbnailColor: "#FF9898",
    buttonColor: "#FF9898",
    buttonTextColor: "#333333",
    hyperTextColor: "#FF9898",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#333",
    thumbnailTitleColor: "#333",
  },
  {
    id: "9",
    name: "Navy Skyline Palette",
    backgroundColor: "#2A324B",
    shareColor: "#2A324B",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFE4B5",
    buttonColor: "#FFE4B5",
    buttonTextColor: "#2A324B",
    hyperTextColor: "#FFE4B5",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#2A324B",
    thumbnailTitleColor: "#2A324B",
  },
  {
    id: "10",
    name: "Pink Horizon Palette",
    backgroundColor: "#FFB6C1",
    shareColor: "#FFB6C1",
    textColor: "#333333",
    thumbnailColor: "#0A68B6",
    buttonColor: "#0A68B6",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#0A68B6",
    hyperTitleColor: "#333333",
    titleColor: "#333333", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#0F0F0F",
    tryNowButtonColor: "#FFB6C1",
    thumbnailTitleColor: "#FFF",
  },
  {
    id: "11",
    name: "Deep Sea palette",
    backgroundColor: "#3B5998",
    shareColor: "#3B5998",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFFFFF",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#3B5998",
    hyperTextColor: "#FFFFFF",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#3B5998",
    thumbnailTitleColor: "#3B5998",
  },
  {
    id: "12",
    name: "Lavender Earth Palette",
    backgroundColor: "#C7AABC",
    textColor: "#000000",
    thumbnailColor: "#834949",
    buttonColor: "#834949",
    shareColor: "#834949",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#834949",
    hyperTitleColor: "#834949",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#834949",
    thumbnailTitleColor: "#FFF",
  },
  {
    id: "13",
    name: "Sandy Snow Palette",
    backgroundColor: "#D49C6B",
    shareColor: "#D49C6B",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFFFFF",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#000000",
    hyperTextColor: "#FFFFFF",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#D49C6B",
    thumbnailTitleColor: "#000",
  },
  {
    id: "14",
    name: "Lemon Meadow Palette",
    backgroundColor: "#FFFF94",
    textColor: "#000000",
    thumbnailColor: "#5A845A",
    buttonColor: "#5A845A",
    shareColor: "#5A845A",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#000000",
    hyperTitleColor: "#000000",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#5A845A",
    thumbnailTitleColor: "#FFF",
  },
  {
    id: "15",
    name: "Minty Blossom Palette",
    backgroundColor: "#4CAF50",
    shareColor: "#4CAF50",
    textColor: "#FFFFFF",
    thumbnailColor: "#FFE4B5",
    buttonColor: "#FFE4B5",
    buttonTextColor: "#000000",
    hyperTextColor: "#000000",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#4CAF50",
    thumbnailTitleColor: "#000",
  },
  {
    id: "16",
    name: "Snowy Glade Palette",
    backgroundColor: "#E2E2E2",
    shareColor: "#5A845A",
    textColor: "#000000",
    thumbnailColor: "#5A845A",
    buttonColor: "#5A845A",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#000000",
    hyperTitleColor: "#5A845A",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#5A845A",
    thumbnailTitleColor: "#FFF",
  },
  {
    id: "17",
    name: "Sunlit Cream Palette",
    backgroundColor: "#E8E59C",
    shareColor: "#E8E59C",
    textColor: "#000000",
    thumbnailColor: "#FFFFFF",
    buttonColor: "#FFFFFF",
    buttonTextColor: "#000000",
    hyperTextColor: "#000000",
    hyperTitleColor: "#000000",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#0F0F0F",
    tryNowButtonColor: "#E8E59C",
    thumbnailTitleColor: "#000",
  },
  {
    id: "18",
    name: "DarK Sky Palette",
    backgroundColor: "#2A324B",
    shareColor: "#2A324B",
    textColor: "#FFFFFF",
    thumbnailColor: "#C7CCDB",
    buttonColor: "#C7CCDB",
    buttonTextColor: "#000000",
    hyperTextColor: "#FFFFFF",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#2A324B",
    thumbnailTitleColor: "#000",
  },
  {
    id: "19",
    name: "Vanilla Rose Palette",
    backgroundColor: "#F5F5DC",
    textColor: "#000000",
    thumbnailColor: "#A9225B",
    buttonColor: "#A9225B",
    shareColor: "#A9225B",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#A9225B",
    hyperTitleColor: "#000000",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#A9225B",
    thumbnailTitleColor: "#FFFFFF",
  },
  {
    id: "20",
    name: "Berry Bloom Palette",
    backgroundColor: "#A9225B",
    shareColor: "#A9225B",
    textColor: "#FFFFFF",
    thumbnailColor: "#F5F5DC",
    buttonColor: "#F5F5DC",
    buttonTextColor: "#000000",
    hyperTextColor: "#FFFFFF",
    hyperTitleColor: "#FFFFFF",
    titleColor: "#FFFFFF", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#A9225B",
    thumbnailTitleColor: "#000",
  },
  {
    id: "21",
    name: "White Wave Palette",
    backgroundColor: "#F5F5F5",
    textColor: "#000000",
    thumbnailColor: "#2677CC",
    buttonColor: "#2677CC",
    shareColor: "#2677CC",
    buttonTextColor: "#FFFFFF",
    hyperTextColor: "#2677CC",
    hyperTitleColor: "#000",
    titleColor: "#000000", // Assigned textColor to titleColor
    tryNowButtonTextColor: "#FFFFFF",
    tryNowButtonColor: "#2677CC",
    thumbnailTitleColor: "#FFFFFF",
  },
];
